# Generated by Django 4.1.4 on 2023-05-11 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0003_fotografia_puclicada'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fotografia',
            old_name='puclicada',
            new_name='publicada',
        ),
    ]
